services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventlive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventlive"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: node:18-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/eventlive
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        echo 'Instalando dependencias...' &&
        npm install &&
        echo 'Generando cliente Prisma...' &&
        npm run prisma:generate &&
        echo 'Ejecutando migraciones...' &&
        npm run prisma:migrate &&
        echo 'Ejecutando seed...' &&
        npm run prisma:seed
      "

volumes:
  postgres_data: 