version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: streamingprotv-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamingprotv-network
    profiles:
      - database
      - all

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamingprotv-app
    restart: always
    environment:
      # Database
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      
      # NextAuth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      
      # Admin
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
      # App
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - app_data:/app/data
    networks:
      - streamingprotv-network
    depends_on:
      - postgres
    profiles:
      - app
      - all

volumes:
  postgres_data:
    name: streamingprotv-db-data
  app_data:
    name: streamingprotv-app-data

networks:
  streamingprotv-network:
    name: streamingprotv-network
    driver: bridge 